services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo
    command: >
      odoo
      --db_host=db
      --db_port=5433
      --db_user=odoo
      --db_password=odoo
      --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "adam@vettsolutions.com"
      PGADMIN_DEFAULT_PASSWORD: "your_strong_password"
    ports:
      - "8080:80"
    depends_on:
      - db  
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  odoo-data:
  db-data:
  pgadmin-data:
